import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/layouts'
import { useAuth } from '../hooks/auth'
import useProducts from '../hooks/use-product'
import styles from '../styles/Home.module.css'

const Home = () => {
  // const { data, error, register,login } = useAuth();
  // if(error) return <div>fail to load</div>;
  // if(!data) return <div>Loading...</div>
  const {data:products,error,create,remove} = useProducts()
  if(!products) return <div>Loading ....</div>
  if(error) return <div>Error</div>
  return (
    <div className={styles.container}>
      <Head>
        <title>Next JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {products.map((product:any,index:any) => (
      <div key={index}>
        {product.name}
        <button onClick={()=> remove(product.id)} className='bg-red-500'>Delete</button>
      </div>
      ))}
        <button onClick={() => create({ id: "11", name: "Product 12" })}>Create</button>
      <main className={styles.main}>
        Main
      </main>
    </div>
  )
}
export default Home
